// コインナビ / Bus Coin Navi — デモ用モックデータ
// 実運用では神奈川中央交通のODPT運賃・停留所・路線データ(GTFS-JP)に差し替える

// 停留所リスト(デモ用・神奈川中央交通エリアを想定した架空区間)
const STOPS = [
  { id: "st01", name: { ja: "橋本駅北口", en: "Hashimoto Sta. North" } },
  { id: "st02", name: { ja: "相模原駅前", en: "Sagamihara Sta." } },
  { id: "st03", name: { ja: "町田バスセンター", en: "Machida Bus Center" } },
  { id: "st04", name: { ja: "淵野辺駅", en: "Fuchinobe Sta." } },
  { id: "st05", name: { ja: "本厚木駅", en: "Hon-Atsugi Sta." } },
];

// 運賃表(デモ用モック。stop間の片道運賃、円)
// 実運用は ckan.odpt.org の「神奈川中央交通 バス運賃情報」を読み込む
const FARE_TABLE = {
  "st01-st02": 220,
  "st01-st03": 360,
  "st01-st04": 280,
  "st01-st05": 590,
  "st02-st03": 310,
  "st02-st04": 180,
  "st02-st05": 470,
  "st03-st04": 340,
  "st03-st05": 650,
  "st04-st05": 410,
};

function getFare(fromId, toId) {
  if (fromId === toId) return 0;
  const key1 = `${fromId}-${toId}`;
  const key2 = `${toId}-${fromId}`;
  return FARE_TABLE[key1] ?? FARE_TABLE[key2] ?? null;
}

// 日本の硬貨・紙幣の額面(大きい順)
const DENOMINATIONS = [1000, 500, 100, 50, 10, 5, 1];

// 指定金額を最小枚数の硬貨・紙幣構成に分解する
function breakdownToCoins(amount) {
  let remaining = amount;
  const result = [];
  for (const d of DENOMINATIONS) {
    const count = Math.floor(remaining / d);
    if (count > 0) {
      result.push({ value: d, count });
      remaining -= d * count;
    }
  }
  return result;
}

// 多言語辞書
const I18N = {
  ja: {
    langName: "日本語",
    dir: "ltr",
    selectLanguage: "言語を選んでください",
    scanQr: "QRコードをスキャン",
    scanQrHint: "運転手が掲示するQRコードを読み取ってください",
    simulateScan: "（デモ）現在の停留所を選択",
    currentStop: "現在の乗車停留所",
    selectDestination: "行き先を選んでください",
    fareIs: "運賃",
    coinsNeeded: "ご用意いただくお金",
    yen: "円",
    coin: "枚",
    showToDriver: "運転手に見せる",
    driverScreenTitle: "現金でお支払いします",
    back: "戻る",
    unit_1000: "1000円札",
    unit_500: "500円玉",
    unit_100: "100円玉",
    unit_50: "50円玉",
    unit_10: "10円玉",
    unit_5: "5円玉",
    unit_1: "1円玉",
  },
  en: {
    langName: "English",
    dir: "ltr",
    selectLanguage: "Please select your language",
    scanQr: "Scan QR Code",
    scanQrHint: "Scan the QR code shown by the driver",
    simulateScan: "(Demo) Select current stop",
    currentStop: "Current boarding stop",
    selectDestination: "Please select your destination",
    fareIs: "Fare",
    coinsNeeded: "Money to prepare",
    yen: "yen",
    coin: "",
    showToDriver: "Show to driver",
    driverScreenTitle: "Paying in cash",
    back: "Back",
    unit_1000: "¥1000 bill",
    unit_500: "¥500 coin",
    unit_100: "¥100 coin",
    unit_50: "¥50 coin",
    unit_10: "¥10 coin",
    unit_5: "¥5 coin",
    unit_1: "¥1 coin",
  },
  zh: {
    langName: "中文（简体）",
    dir: "ltr",
    selectLanguage: "请选择您的语言",
    scanQr: "扫描二维码",
    scanQrHint: "请扫描司机出示的二维码",
    simulateScan: "（演示）选择当前车站",
    currentStop: "当前上车站",
    selectDestination: "请选择目的地",
    fareIs: "车费",
    coinsNeeded: "请准备的钱款",
    yen: "日元",
    coin: "枚",
    showToDriver: "出示给司机",
    driverScreenTitle: "使用现金支付",
    back: "返回",
    unit_1000: "1000日元纸币",
    unit_500: "500日元硬币",
    unit_100: "100日元硬币",
    unit_50: "50日元硬币",
    unit_10: "10日元硬币",
    unit_5: "5日元硬币",
    unit_1: "1日元硬币",
  },
  ko: {
    langName: "한국어",
    dir: "ltr",
    selectLanguage: "언어를 선택해 주세요",
    scanQr: "QR 코드 스캔",
    scanQrHint: "기사님이 제시하는 QR 코드를 스캔해 주세요",
    simulateScan: "(데모) 현재 정류장 선택",
    currentStop: "현재 승차 정류장",
    selectDestination: "목적지를 선택해 주세요",
    fareIs: "요금",
    coinsNeeded: "준비해야 할 돈",
    yen: "엔",
    coin: "개",
    showToDriver: "기사님에게 보여주기",
    driverScreenTitle: "현금으로 지불합니다",
    back: "뒤로",
    unit_1000: "1000엔 지폐",
    unit_500: "500엔 동전",
    unit_100: "100엔 동전",
    unit_50: "50엔 동전",
    unit_10: "10엔 동전",
    unit_5: "5엔 동전",
    unit_1: "1엔 동전",
  },
  es: {
    langName: "Español",
    dir: "ltr",
    selectLanguage: "Seleccione su idioma",
    scanQr: "Escanear código QR",
    scanQrHint: "Escanee el código QR que muestra el conductor",
    simulateScan: "(Demo) Seleccionar parada actual",
    currentStop: "Parada de embarque actual",
    selectDestination: "Seleccione su destino",
    fareIs: "Tarifa",
    coinsNeeded: "Dinero a preparar",
    yen: "yenes",
    coin: "",
    showToDriver: "Mostrar al conductor",
    driverScreenTitle: "Pago en efectivo",
    back: "Atrás",
    unit_1000: "billete de 1000 yenes",
    unit_500: "moneda de 500 yenes",
    unit_100: "moneda de 100 yenes",
    unit_50: "moneda de 50 yenes",
    unit_10: "moneda de 10 yenes",
    unit_5: "moneda de 5 yenes",
    unit_1: "moneda de 1 yen",
  },
  fr: {
    langName: "Français",
    dir: "ltr",
    selectLanguage: "Veuillez choisir votre langue",
    scanQr: "Scanner le QR code",
    scanQrHint: "Scannez le QR code présenté par le chauffeur",
    simulateScan: "(Démo) Choisir l'arrêt actuel",
    currentStop: "Arrêt d'embarquement actuel",
    selectDestination: "Veuillez choisir votre destination",
    fareIs: "Tarif",
    coinsNeeded: "Montant à préparer",
    yen: "yens",
    coin: "",
    showToDriver: "Montrer au chauffeur",
    driverScreenTitle: "Paiement en espèces",
    back: "Retour",
    unit_1000: "billet de 1000 yens",
    unit_500: "pièce de 500 yens",
    unit_100: "pièce de 100 yens",
    unit_50: "pièce de 50 yens",
    unit_10: "pièce de 10 yens",
    unit_5: "pièce de 5 yens",
    unit_1: "pièce de 1 yen",
  },
  it: {
    langName: "Italiano",
    dir: "ltr",
    selectLanguage: "Seleziona la tua lingua",
    scanQr: "Scansiona codice QR",
    scanQrHint: "Scansiona il codice QR mostrato dall'autista",
    simulateScan: "(Demo) Seleziona fermata attuale",
    currentStop: "Fermata di salita attuale",
    selectDestination: "Seleziona la destinazione",
    fareIs: "Tariffa",
    coinsNeeded: "Denaro da preparare",
    yen: "yen",
    coin: "",
    showToDriver: "Mostra all'autista",
    driverScreenTitle: "Pagamento in contanti",
    back: "Indietro",
    unit_1000: "banconota da 1000 yen",
    unit_500: "moneta da 500 yen",
    unit_100: "moneta da 100 yen",
    unit_50: "moneta da 50 yen",
    unit_10: "moneta da 10 yen",
    unit_5: "moneta da 5 yen",
    unit_1: "moneta da 1 yen",
  },
  ar: {
    langName: "العربية",
    dir: "rtl",
    selectLanguage: "الرجاء اختيار لغتك",
    scanQr: "مسح رمز QR",
    scanQrHint: "امسح رمز QR الذي يعرضه السائق",
    simulateScan: "(تجريبي) اختر المحطة الحالية",
    currentStop: "محطة الركوب الحالية",
    selectDestination: "الرجاء اختيار وجهتك",
    fareIs: "الأجرة",
    coinsNeeded: "المبلغ الذي يجب تجهيزه",
    yen: "ين",
    coin: "قطعة",
    showToDriver: "أظهر للسائق",
    driverScreenTitle: "الدفع نقداً",
    back: "رجوع",
    unit_1000: "ورقة 1000 ين",
    unit_500: "عملة 500 ين",
    unit_100: "عملة 100 ين",
    unit_50: "عملة 50 ين",
    unit_10: "عملة 10 ين",
    unit_5: "عملة 5 ين",
    unit_1: "عملة 1 ين",
  },
  id: {
    langName: "Bahasa Indonesia",
    dir: "ltr",
    selectLanguage: "Silakan pilih bahasa Anda",
    scanQr: "Pindai kode QR",
    scanQrHint: "Pindai kode QR yang ditunjukkan oleh sopir",
    simulateScan: "(Demo) Pilih halte saat ini",
    currentStop: "Halte naik saat ini",
    selectDestination: "Silakan pilih tujuan Anda",
    fareIs: "Tarif",
    coinsNeeded: "Uang yang perlu disiapkan",
    yen: "yen",
    coin: "keping",
    showToDriver: "Tunjukkan ke sopir",
    driverScreenTitle: "Membayar tunai",
    back: "Kembali",
    unit_1000: "uang kertas 1000 yen",
    unit_500: "koin 500 yen",
    unit_100: "koin 100 yen",
    unit_50: "koin 50 yen",
    unit_10: "koin 10 yen",
    unit_5: "koin 5 yen",
    unit_1: "koin 1 yen",
  },
  ms: {
    langName: "Bahasa Melayu",
    dir: "ltr",
    selectLanguage: "Sila pilih bahasa anda",
    scanQr: "Imbas kod QR",
    scanQrHint: "Imbas kod QR yang ditunjukkan oleh pemandu",
    simulateScan: "(Demo) Pilih perhentian semasa",
    currentStop: "Perhentian menaiki semasa",
    selectDestination: "Sila pilih destinasi anda",
    fareIs: "Tambang",
    coinsNeeded: "Wang yang perlu disediakan",
    yen: "yen",
    coin: "keping",
    showToDriver: "Tunjukkan kepada pemandu",
    driverScreenTitle: "Bayaran tunai",
    back: "Kembali",
    unit_1000: "wang kertas 1000 yen",
    unit_500: "duit syiling 500 yen",
    unit_100: "duit syiling 100 yen",
    unit_50: "duit syiling 50 yen",
    unit_10: "duit syiling 10 yen",
    unit_5: "duit syiling 5 yen",
    unit_1: "duit syiling 1 yen",
  },
};

const LANGUAGES = Object.keys(I18N);
