// コインナビ / Bus Coin Navi — デモ用モックデータ
// 実運用では神奈川中央交通のODPT運賃・停留所・路線データ(GTFS-JP)に差し替える

// 停留所リスト(デモ用・神奈川中央交通エリアを想定。緯度経度は実際の最寄駅付近の座標)
const STOPS = [
  { id: "st01", name: { ja: "橋本駅北口", en: "Hashimoto Sta. North" }, lat: 35.5936, lng: 139.3454 },
  { id: "st02", name: { ja: "相模原駅前", en: "Sagamihara Sta." }, lat: 35.5720, lng: 139.3735 },
  { id: "st03", name: { ja: "町田バスセンター", en: "Machida Bus Center" }, lat: 35.5461, lng: 139.4472 },
  { id: "st04", name: { ja: "淵野辺駅", en: "Fuchinobe Sta." }, lat: 35.5661, lng: 139.3948 },
  { id: "st05", name: { ja: "本厚木駅", en: "Hon-Atsugi Sta." }, lat: 35.4426, lng: 139.3636 },
];

// 整理券番号(バス乗車時に取る番号札)と停留所の対応(デモ用・この路線の乗車順)
// 実運用は事業者のGTFS-JP運賃データが持つ運賃区界(fare stage)番号に合わせる
const SEIRIKEN_ROUTE_ORDER = ["st01", "st02", "st04", "st03", "st05"];

function getStopBySeirikenNumber(number) {
  const stopId = SEIRIKEN_ROUTE_ORDER[number - 1];
  return STOPS.find((s) => s.id === stopId) || null;
}

// 2点間の距離(メートル)をハーバサイン公式で計算
function distanceMeters(lat1, lng1, lat2, lng2) {
  const R = 6371000;
  const toRad = (d) => (d * Math.PI) / 180;
  const dLat = toRad(lat2 - lat1);
  const dLng = toRad(lng2 - lng1);
  const a =
    Math.sin(dLat / 2) ** 2 +
    Math.cos(toRad(lat1)) * Math.cos(toRad(lat2)) * Math.sin(dLng / 2) ** 2;
  return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
}

// 現在地から最も近い停留所を返す(第3引数で対象の停留所リストを差し替え可能。省略時はSTOPS)
function findNearestStop(lat, lng, stopsList) {
  const list = stopsList || STOPS;
  let nearest = null;
  let minDist = Infinity;
  for (const stop of list) {
    const d = distanceMeters(lat, lng, stop.lat, stop.lng);
    if (d < minDist) {
      minDist = d;
      nearest = stop;
    }
  }
  return { stop: nearest, distanceMeters: minDist };
}

// 運賃表(デモ用モック。stop間の片道運賃、円)
// 実運用は ckan.odpt.org の「神奈川中央交通 バス運賃情報」を読み込む
const FARE_TABLE = {
  "st01-st02": 220,
  "st01-st03": 360,
  "st01-st04": 280,
  "st01-st05": 590,
  "st02-st03": 310,
  "st02-st04": 180,
  "st02-st05": 470,
  "st03-st04": 340,
  "st03-st05": 650,
  "st04-st05": 410,
};

function getFare(fromId, toId) {
  if (fromId === toId) return 0;
  const key1 = `${fromId}-${toId}`;
  const key2 = `${toId}-${fromId}`;
  return FARE_TABLE[key1] ?? FARE_TABLE[key2] ?? null;
}

// 日本の硬貨・紙幣の額面(大きい順)
const DENOMINATIONS = [1000, 500, 100, 50, 10, 5, 1];

// 指定金額を最小枚数の硬貨・紙幣構成に分解する
function breakdownToCoins(amount) {
  let remaining = amount;
  const result = [];
  for (const d of DENOMINATIONS) {
    const count = Math.floor(remaining / d);
    if (count > 0) {
      result.push({ value: d, count });
      remaining -= d * count;
    }
  }
  return result;
}

// 多言語辞書
const I18N = {
  ja: {
    langName: "日本語",
    dir: "ltr",
    selectLanguage: "言語を選んでください",
    detecting: "現在地から乗車停留所を確認しています…",
    waitingNear: "近くで待機中:",
    estimatedFareNote: "＊この区間の正式な運賃データがないため、距離からの概算額です",
    addStopLink: "＋現在地をテスト用バス停として登録",
    addStopTitle: "現在地をバス停として登録",
    addStopNamePrompt: "バス停の名前を入力してください",
    addStopSave: "登録する",
    addStopSaved: "登録しました",
    boardedAt: "乗車停留所",
    wrongStop: "違う場合はこちら（手動で選ぶ）",
    ridingTitle: "バスにご乗車中です",
    ridingHint: "降りるときは、運転手が提示するQRコードを読み取ってください",
    getOffButton: "降ります（QRを読み取る）",
    scanDestHint: "降りる停留所で、運転手が提示するQRコードを読み取ってください",
    locationDenied: "位置情報を取得できませんでした。手動で選択してください",
    scanQr: "QRコードをスキャン",
    scanQrHint: "運転手が掲示するQRコードを読み取ってください",
    simulateScan: "（デモ）停留所を手動選択",
    stopNameTab: "停留所名で選ぶ",
    seirikenTab: "整理券番号で選ぶ",
    seirikenPrompt: "整理券に書かれている番号を選んでください",
    seirikenNumberLabel: "番号",
    currentStop: "現在の乗車停留所",
    selectDestination: "行き先を選んでください",
    fareIs: "運賃",
    coinsNeeded: "ご用意いただくお金",
    yen: "円",
    coin: "枚",
    showToDriver: "運転手に見せる",
    driverScreenTitle: "現金でお支払いします",
    back: "戻る",
    unit_1000: "1000円札",
    unit_500: "500円玉",
    unit_100: "100円玉",
    unit_50: "50円玉",
    unit_10: "10円玉",
    unit_5: "5円玉",
    unit_1: "1円玉",
  },
  en: {
    langName: "English",
    dir: "ltr",
    selectLanguage: "Please select your language",
    detecting: "Detecting your boarding stop from your location…",
    waitingNear: "Waiting near:",
    estimatedFareNote: "*No official fare data for this route; estimated from distance",
    addStopLink: "+ Register current location as a test stop",
    addStopTitle: "Register current location as a stop",
    addStopNamePrompt: "Enter a name for this stop",
    addStopSave: "Save",
    addStopSaved: "Saved",
    boardedAt: "Boarding stop",
    wrongStop: "Not correct? Select manually",
    ridingTitle: "You are riding the bus",
    ridingHint: "When you get off, scan the QR code shown by the driver",
    getOffButton: "Get off (Scan QR)",
    scanDestHint: "At the stop where you get off, scan the QR code shown by the driver",
    locationDenied: "Could not get your location. Please select manually",
    scanQr: "Scan QR Code",
    scanQrHint: "Scan the QR code shown by the driver",
    simulateScan: "(Demo) Select stop manually",
    stopNameTab: "By stop name",
    seirikenTab: "By ticket number",
    seirikenPrompt: "Select the number printed on your boarding ticket",
    seirikenNumberLabel: "No.",
    currentStop: "Current boarding stop",
    selectDestination: "Please select your destination",
    fareIs: "Fare",
    coinsNeeded: "Money to prepare",
    yen: "yen",
    coin: "",
    showToDriver: "Show to driver",
    driverScreenTitle: "Paying in cash",
    back: "Back",
    unit_1000: "¥1000 bill",
    unit_500: "¥500 coin",
    unit_100: "¥100 coin",
    unit_50: "¥50 coin",
    unit_10: "¥10 coin",
    unit_5: "¥5 coin",
    unit_1: "¥1 coin",
  },
  zh: {
    langName: "中文（简体）",
    dir: "ltr",
    selectLanguage: "请选择您的语言",
    detecting: "正在根据您的位置确认上车站…",
    waitingNear: "正在等待附近:",
    estimatedFareNote: "＊此区间无正式票价数据，为距离估算金额",
    addStopLink: "＋将当前位置注册为测试用车站",
    addStopTitle: "将当前位置注册为车站",
    addStopNamePrompt: "请输入车站名称",
    addStopSave: "注册",
    addStopSaved: "已注册",
    boardedAt: "上车站",
    wrongStop: "不正确？手动选择",
    ridingTitle: "您正在乘坐巴士",
    ridingHint: "下车时，请扫描司机出示的二维码",
    getOffButton: "下车（扫描二维码）",
    scanDestHint: "在您下车的车站，请扫描司机出示的二维码",
    locationDenied: "无法获取您的位置，请手动选择",
    scanQr: "扫描二维码",
    scanQrHint: "请扫描司机出示的二维码",
    simulateScan: "（演示）手动选择车站",
    stopNameTab: "按车站名称选择",
    seirikenTab: "按整理券号码选择",
    seirikenPrompt: "请选择乘车券上印刷的号码",
    seirikenNumberLabel: "号码",
    currentStop: "当前上车站",
    selectDestination: "请选择目的地",
    fareIs: "车费",
    coinsNeeded: "请准备的钱款",
    yen: "日元",
    coin: "枚",
    showToDriver: "出示给司机",
    driverScreenTitle: "使用现金支付",
    back: "返回",
    unit_1000: "1000日元纸币",
    unit_500: "500日元硬币",
    unit_100: "100日元硬币",
    unit_50: "50日元硬币",
    unit_10: "10日元硬币",
    unit_5: "5日元硬币",
    unit_1: "1日元硬币",
  },
  ko: {
    langName: "한국어",
    dir: "ltr",
    selectLanguage: "언어를 선택해 주세요",
    detecting: "현재 위치로 승차 정류장을 확인하고 있습니다…",
    waitingNear: "대기 중인 정류장:",
    estimatedFareNote: "＊이 구간의 공식 요금 데이터가 없어 거리 기반 추정 금액입니다",
    addStopLink: "＋현재 위치를 테스트용 정류장으로 등록",
    addStopTitle: "현재 위치를 정류장으로 등록",
    addStopNamePrompt: "정류장 이름을 입력해 주세요",
    addStopSave: "등록",
    addStopSaved: "등록되었습니다",
    boardedAt: "승차 정류장",
    wrongStop: "다른가요? 수동으로 선택",
    ridingTitle: "버스에 탑승 중입니다",
    ridingHint: "내리실 때, 기사님이 제시하는 QR 코드를 스캔해 주세요",
    getOffButton: "하차 (QR 스캔)",
    scanDestHint: "내리는 정류장에서 기사님이 제시하는 QR 코드를 스캔해 주세요",
    locationDenied: "위치 정보를 가져올 수 없습니다. 수동으로 선택해 주세요",
    scanQr: "QR 코드 스캔",
    scanQrHint: "기사님이 제시하는 QR 코드를 스캔해 주세요",
    simulateScan: "(데모) 정류장 수동 선택",
    stopNameTab: "정류장 이름으로 선택",
    seirikenTab: "정리권 번호로 선택",
    seirikenPrompt: "승차권에 인쇄된 번호를 선택해 주세요",
    seirikenNumberLabel: "번호",
    currentStop: "현재 승차 정류장",
    selectDestination: "목적지를 선택해 주세요",
    fareIs: "요금",
    coinsNeeded: "준비해야 할 돈",
    yen: "엔",
    coin: "개",
    showToDriver: "기사님에게 보여주기",
    driverScreenTitle: "현금으로 지불합니다",
    back: "뒤로",
    unit_1000: "1000엔 지폐",
    unit_500: "500엔 동전",
    unit_100: "100엔 동전",
    unit_50: "50엔 동전",
    unit_10: "10엔 동전",
    unit_5: "5엔 동전",
    unit_1: "1엔 동전",
  },
  es: {
    langName: "Español",
    dir: "ltr",
    selectLanguage: "Seleccione su idioma",
    detecting: "Detectando su parada de embarque según su ubicación…",
    waitingNear: "Esperando cerca de:",
    estimatedFareNote: "*No hay datos oficiales de tarifa para este tramo; estimado por distancia",
    addStopLink: "+ Registrar ubicación actual como parada de prueba",
    addStopTitle: "Registrar ubicación actual como parada",
    addStopNamePrompt: "Ingrese un nombre para esta parada",
    addStopSave: "Guardar",
    addStopSaved: "Guardado",
    boardedAt: "Parada de embarque",
    wrongStop: "¿No es correcto? Seleccionar manualmente",
    ridingTitle: "Está viajando en el autobús",
    ridingHint: "Al bajar, escanee el código QR que muestra el conductor",
    getOffButton: "Bajar (Escanear QR)",
    scanDestHint: "En la parada donde baja, escanee el código QR que muestra el conductor",
    locationDenied: "No se pudo obtener su ubicación. Seleccione manualmente",
    scanQr: "Escanear código QR",
    scanQrHint: "Escanee el código QR que muestra el conductor",
    simulateScan: "(Demo) Seleccionar parada manualmente",
    stopNameTab: "Por nombre de parada",
    seirikenTab: "Por número de billete",
    seirikenPrompt: "Seleccione el número impreso en su billete",
    seirikenNumberLabel: "N.º",
    currentStop: "Parada de embarque actual",
    selectDestination: "Seleccione su destino",
    fareIs: "Tarifa",
    coinsNeeded: "Dinero a preparar",
    yen: "yenes",
    coin: "",
    showToDriver: "Mostrar al conductor",
    driverScreenTitle: "Pago en efectivo",
    back: "Atrás",
    unit_1000: "billete de 1000 yenes",
    unit_500: "moneda de 500 yenes",
    unit_100: "moneda de 100 yenes",
    unit_50: "moneda de 50 yenes",
    unit_10: "moneda de 10 yenes",
    unit_5: "moneda de 5 yenes",
    unit_1: "moneda de 1 yen",
  },
  fr: {
    langName: "Français",
    dir: "ltr",
    selectLanguage: "Veuillez choisir votre langue",
    detecting: "Détection de votre arrêt d'embarquement selon votre position…",
    waitingNear: "En attente près de :",
    estimatedFareNote: "*Pas de donnée tarifaire officielle pour ce trajet ; estimation par distance",
    addStopLink: "+ Enregistrer la position actuelle comme arrêt de test",
    addStopTitle: "Enregistrer la position actuelle comme arrêt",
    addStopNamePrompt: "Entrez un nom pour cet arrêt",
    addStopSave: "Enregistrer",
    addStopSaved: "Enregistré",
    boardedAt: "Arrêt d'embarquement",
    wrongStop: "Incorrect ? Sélectionner manuellement",
    ridingTitle: "Vous êtes dans le bus",
    ridingHint: "Pour descendre, scannez le QR code présenté par le chauffeur",
    getOffButton: "Descendre (Scanner QR)",
    scanDestHint: "À l'arrêt où vous descendez, scannez le QR code présenté par le chauffeur",
    locationDenied: "Impossible d'obtenir votre position. Sélectionnez manuellement",
    scanQr: "Scanner le QR code",
    scanQrHint: "Scannez le QR code présenté par le chauffeur",
    simulateScan: "(Démo) Choisir l'arrêt manuellement",
    stopNameTab: "Par nom d'arrêt",
    seirikenTab: "Par numéro de ticket",
    seirikenPrompt: "Sélectionnez le numéro imprimé sur votre ticket",
    seirikenNumberLabel: "N°",
    currentStop: "Arrêt d'embarquement actuel",
    selectDestination: "Veuillez choisir votre destination",
    fareIs: "Tarif",
    coinsNeeded: "Montant à préparer",
    yen: "yens",
    coin: "",
    showToDriver: "Montrer au chauffeur",
    driverScreenTitle: "Paiement en espèces",
    back: "Retour",
    unit_1000: "billet de 1000 yens",
    unit_500: "pièce de 500 yens",
    unit_100: "pièce de 100 yens",
    unit_50: "pièce de 50 yens",
    unit_10: "pièce de 10 yens",
    unit_5: "pièce de 5 yens",
    unit_1: "pièce de 1 yen",
  },
  it: {
    langName: "Italiano",
    dir: "ltr",
    selectLanguage: "Seleziona la tua lingua",
    detecting: "Rilevamento della fermata di salita in base alla posizione…",
    waitingNear: "In attesa vicino a:",
    estimatedFareNote: "*Nessun dato tariffario ufficiale per questo tratto; stima basata sulla distanza",
    addStopLink: "+ Registra la posizione attuale come fermata di prova",
    addStopTitle: "Registra la posizione attuale come fermata",
    addStopNamePrompt: "Inserisci un nome per questa fermata",
    addStopSave: "Salva",
    addStopSaved: "Salvato",
    boardedAt: "Fermata di salita",
    wrongStop: "Non corretto? Seleziona manualmente",
    ridingTitle: "Sei a bordo dell'autobus",
    ridingHint: "Per scendere, scansiona il codice QR mostrato dall'autista",
    getOffButton: "Scendere (Scansiona QR)",
    scanDestHint: "Alla fermata in cui scendi, scansiona il codice QR mostrato dall'autista",
    locationDenied: "Impossibile rilevare la posizione. Seleziona manualmente",
    scanQr: "Scansiona codice QR",
    scanQrHint: "Scansiona il codice QR mostrato dall'autista",
    simulateScan: "(Demo) Seleziona fermata manualmente",
    stopNameTab: "Per nome fermata",
    seirikenTab: "Per numero di biglietto",
    seirikenPrompt: "Seleziona il numero stampato sul tuo biglietto",
    seirikenNumberLabel: "N.",
    currentStop: "Fermata di salita attuale",
    selectDestination: "Seleziona la destinazione",
    fareIs: "Tariffa",
    coinsNeeded: "Denaro da preparare",
    yen: "yen",
    coin: "",
    showToDriver: "Mostra all'autista",
    driverScreenTitle: "Pagamento in contanti",
    back: "Indietro",
    unit_1000: "banconota da 1000 yen",
    unit_500: "moneta da 500 yen",
    unit_100: "moneta da 100 yen",
    unit_50: "moneta da 50 yen",
    unit_10: "moneta da 10 yen",
    unit_5: "moneta da 5 yen",
    unit_1: "moneta da 1 yen",
  },
  ar: {
    langName: "العربية",
    dir: "rtl",
    selectLanguage: "الرجاء اختيار لغتك",
    detecting: "جارٍ تحديد محطة الركوب بناءً على موقعك…",
    waitingNear: "بالانتظار بالقرب من:",
    estimatedFareNote: "*لا توجد بيانات أجرة رسمية لهذا القطاع؛ تقدير بناءً على المسافة",
    addStopLink: "+ تسجيل الموقع الحالي كمحطة اختبار",
    addStopTitle: "تسجيل الموقع الحالي كمحطة",
    addStopNamePrompt: "أدخل اسمًا لهذه المحطة",
    addStopSave: "حفظ",
    addStopSaved: "تم الحفظ",
    boardedAt: "محطة الركوب",
    wrongStop: "غير صحيح؟ اختر يدويًا",
    ridingTitle: "أنت الآن على متن الحافلة",
    ridingHint: "عند النزول، امسح رمز QR الذي يعرضه السائق",
    getOffButton: "النزول (مسح QR)",
    scanDestHint: "في المحطة التي تنزل فيها، امسح رمز QR الذي يعرضه السائق",
    locationDenied: "تعذر تحديد موقعك. الرجاء الاختيار يدويًا",
    scanQr: "مسح رمز QR",
    scanQrHint: "امسح رمز QR الذي يعرضه السائق",
    simulateScan: "(تجريبي) اختر المحطة يدويًا",
    stopNameTab: "حسب اسم المحطة",
    seirikenTab: "حسب رقم التذكرة",
    seirikenPrompt: "اختر الرقم المطبوع على تذكرتك",
    seirikenNumberLabel: "رقم",
    currentStop: "محطة الركوب الحالية",
    selectDestination: "الرجاء اختيار وجهتك",
    fareIs: "الأجرة",
    coinsNeeded: "المبلغ الذي يجب تجهيزه",
    yen: "ين",
    coin: "قطعة",
    showToDriver: "أظهر للسائق",
    driverScreenTitle: "الدفع نقداً",
    back: "رجوع",
    unit_1000: "ورقة 1000 ين",
    unit_500: "عملة 500 ين",
    unit_100: "عملة 100 ين",
    unit_50: "عملة 50 ين",
    unit_10: "عملة 10 ين",
    unit_5: "عملة 5 ين",
    unit_1: "عملة 1 ين",
  },
  id: {
    langName: "Bahasa Indonesia",
    dir: "ltr",
    selectLanguage: "Silakan pilih bahasa Anda",
    detecting: "Mendeteksi halte naik Anda berdasarkan lokasi…",
    waitingNear: "Menunggu dekat:",
    estimatedFareNote: "*Tidak ada data tarif resmi untuk rute ini; perkiraan berdasarkan jarak",
    addStopLink: "+ Daftarkan lokasi saat ini sebagai halte uji coba",
    addStopTitle: "Daftarkan lokasi saat ini sebagai halte",
    addStopNamePrompt: "Masukkan nama untuk halte ini",
    addStopSave: "Simpan",
    addStopSaved: "Tersimpan",
    boardedAt: "Halte naik",
    wrongStop: "Tidak tepat? Pilih secara manual",
    ridingTitle: "Anda sedang naik bus",
    ridingHint: "Saat turun, pindai kode QR yang ditunjukkan oleh sopir",
    getOffButton: "Turun (Pindai QR)",
    scanDestHint: "Di halte tempat Anda turun, pindai kode QR yang ditunjukkan oleh sopir",
    locationDenied: "Tidak dapat mendeteksi lokasi Anda. Silakan pilih secara manual",
    scanQr: "Pindai kode QR",
    scanQrHint: "Pindai kode QR yang ditunjukkan oleh sopir",
    simulateScan: "(Demo) Pilih halte secara manual",
    stopNameTab: "Berdasarkan nama halte",
    seirikenTab: "Berdasarkan nomor tiket",
    seirikenPrompt: "Pilih nomor yang tercetak pada tiket Anda",
    seirikenNumberLabel: "No.",
    currentStop: "Halte naik saat ini",
    selectDestination: "Silakan pilih tujuan Anda",
    fareIs: "Tarif",
    coinsNeeded: "Uang yang perlu disiapkan",
    yen: "yen",
    coin: "keping",
    showToDriver: "Tunjukkan ke sopir",
    driverScreenTitle: "Membayar tunai",
    back: "Kembali",
    unit_1000: "uang kertas 1000 yen",
    unit_500: "koin 500 yen",
    unit_100: "koin 100 yen",
    unit_50: "koin 50 yen",
    unit_10: "koin 10 yen",
    unit_5: "koin 5 yen",
    unit_1: "koin 1 yen",
  },
  ms: {
    langName: "Bahasa Melayu",
    dir: "ltr",
    selectLanguage: "Sila pilih bahasa anda",
    detecting: "Mengesan perhentian menaiki anda berdasarkan lokasi…",
    waitingNear: "Menunggu berhampiran:",
    estimatedFareNote: "*Tiada data tambang rasmi untuk laluan ini; anggaran berdasarkan jarak",
    addStopLink: "+ Daftarkan lokasi semasa sebagai perhentian ujian",
    addStopTitle: "Daftarkan lokasi semasa sebagai perhentian",
    addStopNamePrompt: "Masukkan nama untuk perhentian ini",
    addStopSave: "Simpan",
    addStopSaved: "Disimpan",
    boardedAt: "Perhentian menaiki",
    wrongStop: "Tidak betul? Pilih secara manual",
    ridingTitle: "Anda sedang menaiki bas",
    ridingHint: "Semasa turun, imbas kod QR yang ditunjukkan oleh pemandu",
    getOffButton: "Turun (Imbas QR)",
    scanDestHint: "Di perhentian tempat anda turun, imbas kod QR yang ditunjukkan oleh pemandu",
    locationDenied: "Tidak dapat mengesan lokasi anda. Sila pilih secara manual",
    scanQr: "Imbas kod QR",
    scanQrHint: "Imbas kod QR yang ditunjukkan oleh pemandu",
    simulateScan: "(Demo) Pilih perhentian secara manual",
    stopNameTab: "Mengikut nama perhentian",
    seirikenTab: "Mengikut nombor tiket",
    seirikenPrompt: "Pilih nombor yang dicetak pada tiket anda",
    seirikenNumberLabel: "No.",
    currentStop: "Perhentian menaiki semasa",
    selectDestination: "Sila pilih destinasi anda",
    fareIs: "Tambang",
    coinsNeeded: "Wang yang perlu disediakan",
    yen: "yen",
    coin: "keping",
    showToDriver: "Tunjukkan kepada pemandu",
    driverScreenTitle: "Bayaran tunai",
    back: "Kembali",
    unit_1000: "wang kertas 1000 yen",
    unit_500: "duit syiling 500 yen",
    unit_100: "duit syiling 100 yen",
    unit_50: "duit syiling 50 yen",
    unit_10: "duit syiling 10 yen",
    unit_5: "duit syiling 5 yen",
    unit_1: "duit syiling 1 yen",
  },
};

const LANGUAGES = Object.keys(I18N);
